### ISSUE TITLE
Select incremental data from a table

### ISSUE THREAD

**Issue by sofianito** [jprante/elasticsearch-river-jdbc#402]
I'm running the following example taken from the river-jdbc tests, and it seems that $river.state.last_active_begin timestamp value is always greater than the modified table column value.

My environment:
DB: MySQL 5.6
ES: I've tried with ES 1.3.4.4 + jdbc-river 1.3.4 and ES 1.4.0.3.Beta1 + jdbc-river 1.4.0.Beta1

To reproduce the issue, I scheduled the command below with the SQL condition:
**a) modified > ? :** The query doesn't return any result, and no document is indexed. 

*INFO: pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@63c86506 complete: river jdbc/mysql metrics: 0 rows, 0.0 mean, (0.0 0.0 0.0), ingest metrics: elapsed 0 seconds, 0.0 bytes bytes, 0.0 bytes avg, 0 MB/s*

**b) modified < ? :** The query return one row and one document is indexed.

*INFO: pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@ac49d10 complete: river jdbc/mysql metrics: 1 rows, 0.03325177780630042 mean, (0.0 0.0 0.0), ingest metrics: elapsed 0 seconds, 68.0 bytes bytes, 34.0 bytes avg, 0 MB/s*

```
create table logs (modified timestamp, message varchar(32));

insert into logs (modified, message) values(utc_timestamp(), "msg1");
commit;
```

Note: In both use cases,  I update the **modified** table column value before the jdbc-river is triggered.

```
PUT _river/mysql/_meta
{
  "type": "jdbc",
  "schedule": "0 0-59 0-23 ? * *",
  "jdbc": {
  	"url": "jdbc:mysql://localhost:3306/test",
	"user": "mysqluser",
	"password": "mysqlpwd",
	"sql": [
	  {
	    "statement" : "select message from logs where modified > ?",
            "parameter" : [ "$river.state.last_active_begin" ]
    }
   ],
   "index": "myindex",
   "type": "mytype"
   }
}
```

**Comment by ssoto** [comment]
Try making a SQL INSERT query each minute like:
```
PUT _river/test_query/_meta 
{
    "type" : "jdbc",
    "schedule" : "0 0-59 0-23 ? * *",
    "jdbc" : {
        "url" : "jdbc:mysql://kamisama:3306/test",
        "user" : "<user>",
        "password" : "<password>",
        "sql" : {
                "statement" : "INSERT INTO ES_indexing_meta VALUES (?, ?);",
                "parameter" : [ "$last.sql.sequence.start", "$last.sql.sequence.end"]
            },
        "index" : "my_jdbc_river_index",
        "type" : "my_jdbc_river_type"
    }
}
```

You will need to create a table like:
```
CREATE DATABASE test;
CREATE TABLE IF NOT EXISTS 
`ES_indexing_meta` ( 
  `start` timestamp NOT NULL , 
  `end` timestamp NOT NULL, );
```

**Comment by StevenLeRoux** [comment]
Also reported in #484

**Comment by StevenLeRoux** [comment]
Pull Request  #489 submitted.
