### ISSUE TITLE
record not delete from es after delete it in mysql

### ISSUE THREAD

**Issue by luthur** [jprante/elasticsearch-river-jdbc#436]
Here is my feeder.sh
    #!/bin/sh
    DIR=/home/binlei/elasticsearch-1.4.2/plugins/jdbc
    export ES_HOME=/home/binlei/elasticsearch-1.4.2

    echo '
    {
        "elasticsearch" : {
             "cluster" : "gtb",
             "host" : "localhost",
             "port" : 9300
        },
        "type" : "jdbc",
        "jdbc" : {
            "url" : "jdbc:mysql://gt1:3306/gt_page?charset=utf8",
            "user" : "root",
            "password" : "root",
            "sql" : "SELECT *, id as \"_id\" FROM models",
            "index" : "test",
            "type": "test"
          }
    }
    ' | java \
        -cp "${DIR}/*" \
        org.xbib.elasticsearch.plugin.jdbc.feeder.Runner \
        org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder

update record is fine, but delete is not working? What have I missed?

**Comment by jprante** [comment]
You can not expect JDBC river can detect deleted rows in RDBMS.

For this you must set up special SQL command that knows what doc IDs to delete in ES, using _optype `delete`.

**Comment by luthur** [comment]
@jprante I would like to use the time based index, thank you very much. #189
