### ISSUE TITLE
SQL quering with parameter returned by elasticseach

### ISSUE THREAD

**Issue by foxhendrix** [jprante/elasticsearch-river-jdbc#440]
I need pass a parameter to SQL on JDBC_RIVER and this parameter must be returned by some search done on elasticsearch . For example: 

```
 "sql" : [   {   "statement" : "select * from \"some_table\" where id > ?"
                "parameter" : [ "max_value(id) from some_table"  ] <-- Return from some_table at elasticsearch
            }    ],

```

**Comment by ivanlw** [comment]
I guess you need to write a nested SQL sentence to perform this, as far as I know river plugin only accepts one SQL statement, and it doesn't seem to hard to do this:
```
SELECT * FROM some_table WHERE id > (
    SELECT MAX(id) FROM other_table)
)
```

**Comment by foxhendrix** [comment]
Ivanlw, thanks your answer, but, I dont can execute this on datase origin. It's something like this:
I have a table in Oracle that we need do input at elasticsearch the incremental records, but, I can't use the $last.sql.end parameter from RIVER to do this cause my table on oracle don't have a time_stamp column.
I need get the last ID record transported to elasticsearch and run the query at oracle with it. 
I tried find something on web, but I did not find anything.

**Comment by ivanlw** [comment]
I can see your situation now. I have no idea to pick out latest id either.

If I were you, I would import the previous data from Oracle to ES for once, then add a time stamp column for future new added records, then you can import incremental records by comparing to $last.sql.end.

**Comment by foxhendrix** [comment]
Thank you. I'll try find another way. I can't alter production table.
