### ISSUE TITLE
longitude and latitude values from MySQL lost 4 digitals of precision when indexing into ES

### ISSUE THREAD

**Issue by ivanlw** [jprante/elasticsearch-river-jdbc#441]
I'm not sure whether this is my mistake or the river plugin intends to do this.

I have a self-defined geo_point field named **coordinate** and I'm importing the values from MySQL as **coordinate.lon** and **coordinate.lat**. They look like

| coordinate.lon 	| coordinate.lat 	|
| ------------- | ------------- |
| 112.849227     	| -20.263292     	|
| 162.461695     	| -15.382983     	|

However, when they are indexed into ES, all the values has been rounded like

| coordinate.lon 	| coordinate.lat 	|
| ------------- | ------------- |
| 112.84          | -20.26     	|
| 162.46     	        | -15.38     	|

I've tried to index values with longer decimal into ES by sending http requests manually, it succeed to store them. Is there any way to keep more accurate value from MySQL using this river plugin?

**Comment by jprante** [comment]
Yes, you can adjust with `scale` and `rounding` parameter.

**Comment by ivanlw** [comment]
Thanks @jprante 
You really solved our problem!
