### ISSUE TITLE
interval vs schedule

### ISSUE THREAD

**Issue by rmoff** [jprante/elasticsearch-river-jdbc#460]
Hi, 
Thanks for such a great tool. I have one question that is not answered by the (excellent) docs. What is the difference between defining an *interval* on a river, and a *schedule*? Are they the same, or mutually exclusive? If I simply want to pull data from a source DB into ES every couple of minutes, which should I use? 
Edit: I've also seen river definitions using *poll* - is this still valid syntax? 

many thanks.

**Comment by jprante** [comment]
`schedule` is for cron jobs, they are started at a given wall clock time.

`interval` is not controlled by cron, this measure a simply a delay between two runs.

`poll` is no longer valid.

**Comment by rmoff** [comment]
Thanks. So if I want to run something every minute, I can use schedule or interval - any benefit of one over the other? I get cron would give for more flexible scheduling patterns, but I’m looking at simple repetitive periodic load here. 




thanks, Robin.


--

Robin Moffatt

Principal Consultant

M: +44 7841 207 265 • E: robin.moffatt@rittmanmead.com

S: robinmoffatt • T: @rmoff

www.rittmanmead.com




Registered Office : Suite B, First Floor, Moore House, 11 - 13 Black Lion Street, Brighton, BN1 1ND, United Kingdom




Company No. : 6032852

VAT No. : 900 3839 48




Please note that this email communication is intended only for the addressee and may contain confidential or privileged information. The contents of this email may be circulated internally within your organisation only and may not be communicated to third parties without the prior written permission of Rittman Mead Consulting.  This email is not intended nor should it be taken to create any legal relations, contractual or otherwise.

**Comment by jprante** [comment]
No, `interval` does not run every minute. It waits for the specified interval after a run. You have to add the running time of an execution to the interval, which may vary from run to run.

`schedule` may not work as expected when runs overlap. There is a pool of 4 threads but jobs that can not be executed are queued and this may overload the system after a certain amount of time.

**Comment by rmoff** [comment]
Thanks


--

Robin Moffatt

Principal Consultant

M: +44 7841 207 265 • E: robin.moffatt@rittmanmead.com

S: robinmoffatt • T: @rmoff

www.rittmanmead.com




Registered Office : Suite B, First Floor, Moore House, 11 - 13 Black Lion Street, Brighton, BN1 1ND, United Kingdom




Company No. : 6032852

VAT No. : 900 3839 48




Please note that this email communication is intended only for the addressee and may contain confidential or privileged information. The contents of this email may be circulated internally within your organisation only and may not be communicated to third parties without the prior written permission of Rittman Mead Consulting.  This email is not intended nor should it be taken to create any legal relations, contractual or otherwise.
