### ISSUE TITLE
elasticsearch-river-jdbc inserting duplicate record in mysql db

### ISSUE THREAD

**Issue by lakhera2014** [jprante/elasticsearch-river-jdbc#493]
Hi

Sorry I am newbie to Elasticsearch and I am using elasticsearch-river-jdbc to connect to myql database,everything is working fine except for the fact that everytime it run as per schedule its inserting duplicate record.This is what I am using

curl -XPUT 'localhost:9200/_river/my_jdbc_river/_meta' -d '{
    "type" : "jdbc",
    "schedule" : "0 0-59 0-23 ? * *",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/test",
        "user" : "test",
        "password" : "test",
        "sql" : "select * from test"
		}
}'

 I go through some docs where it's mentioned that we can run sql query select based on _id but my question is when we created this river only then this unique id is created and that is created on the Elasticsearch side so as per my understanding mysql has no knowledge about this.Please let me know if I am missing something

**Comment by jprante** [comment]
If you do not declare a _id column in the SQL statement, ES has no idea about a unique id. In that case  a random ID is created.

**Comment by lakhera2014** [comment]
Thanks for your reply,Sorry I am confused here as I assuming mysql has no idea id and its failing with below error 

"sql" : "select id as _id,a1,a2 from test"

[2015-03-10 13:16:00,018][ERROR][river.jdbc.RiverPipeline ] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id' in 'field list'
java.io.IOException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id' in 'field list'

**Comment by jprante** [comment]
You have to provide a unique id from the row data of your result set and put it under _id column label.

**Comment by lakhera2014** [comment]
Thanks once again for your reply..I am following your document https://github.com/jprante/elasticsearch-river-jdbc,can you please let me know if there is any other document which I can follow,where its mentioned in details regarding random id generation and how to create this DB..

**Comment by flyte** [comment]
@lakhera2014 I also wasn't sure about that, but it turns out you need to SELECT one of the fields as '_id' for it to work. Here's the syntax I used which works:

    select *, idvisit as _id from piwik_log_visit

And in the full request:

```
curl -XPUT 'localhost:9200/_river/piwik/_meta' -d '{
    "type": "jdbc",
    "jdbc": {
        "url": "jdbc:mysql://localhost:3306/piwik",
        "user": "elasticsearch",
        "password": "*******",
        "sql": "select *, idvisit as _id from piwik_log_visit",
        "index": "piwik",
        "schedule": "0 0-59 0-23 ? * *"
    }
}'
```

**Comment by lakhera2014** [comment]
@flyte: Thanks a lot man..you saved my day..Because of this issue,I start exploring other products but this works.Thanks once again..Only outstanding issue left is when its writing this data back in elasticsearch,date and format changed to UTC format,for eg: 2015-03-11T00:00:00.000-07:00 and 1970-01-01T10:55:54.000-08:00,is there is any workaround for this..

**Comment by sandesh2014** [comment]
Use this within jdbc which will resolve your issue.

"timezone" : "TimeZone.getDefault()",

**Comment by lakhera2014** [comment]
@sandesh2014: Thanks Sandesh..Even after adding that parameter..Still facing the same issue

date: 2015-03-11T00:00:00.000Z
time: 1970-01-01T10:31:34.000Z

**Comment by sandesh2014** [comment]
delete the existing river and index. Recreate index and river with the timezone attribute and that should work.

**Comment by lakhera2014** [comment]
@sandesh2014: Yup exactly I did the same thing 

curl -XDELETE 'localhost:9200/_river/my_jdbc_river/'

To be on the safer side..I restarted elasticsearch ..but still its storing in UTC format

This is how it's on mysql side
+----------+------------+
|| date       | time     | 
+----------+------------+
| 2015-03-11 | 10:31:34 |

**Comment by sandesh2014** [comment]
Can you let me know in what format it is being stored in Elasticsearch and what format you have on your mysql?

**Comment by lakhera2014** [comment]
Please find the details

| Field         | Type          | Null | Key | Default | Extra |
+---------------+---------------+------+-----+---------+-------+
| date          | date          | YES  |     | NULL    |       |
| time          | time          | YES  |     | NULL    |       |

{
_index: jdbc
_type: jdbc
_id: r45
_version: 1
_score: 1
_source: {
date: 2015-03-11T00:00:00.000Z
time: 1970-01-01T10:55:54.000Z
}
}

**Comment by sandesh2014** [comment]
OK got it. You are having date and time as separate columns in your mysql right. Elasticsearch uses Joda timeformat to save date. Hence it is automatically converting your date to datetime. 

In the date field, since you don't have time, it is automatically adding zero's to it.

Regarding the time field, mention the type as string in elasticsearch.

Other option, if you want your actual date and time to be in elasticsearch same as mysql, concatenate both of them before you insert into Elasticsearch.

Hope this helps you

**Comment by lakhera2014** [comment]
@sandesh2014 : You guys are simply awesome..It works..Thanks once again man..
