### ISSUE TITLE
Updating (all and) fresh data

### ISSUE THREAD

**Issue by rmartignoni** [jprante/elasticsearch-river-jdbc#500]
Hi, actually this is a question but I couldn't manage to add the question label to this issue. 

I am using river to send data from a postgres database with ~5M records to ElasticSearch but I'm facing performance issues. The data has to be synced frequently (every 3 minutes) since users are adding/updating information all the time. The whole process take an average of 20 minutes to sync all the data.

My concern is that we need to show users which are online (5 minutes of tolerance). To minimize the amount of data we have to send every time I though that sending only the users which were actually online in the last 5 minutes would greatly increase the overall performance but I am not sure how I would update the users that were not included in the last batch. Basically, the **online** column is *boolean* and I need to update all the documents to **false** and only the fetched ones to **true**. So, I would create a river to sync all the data, shut it down, and create another one to sync the data from "online" users.

I am not sure how to achieve that or even if this is the best approach. Any thoughts?

**Comment by jprante** [comment]
A river approach is quite limited to handle ~5M records - not sure how many updates are in your workload. But putting the load on an RDBMS to select updates from millions of rows can become very heavy soon.

For transporting large sized updates, maybe you want to consider Postgresql logical replication feature?

I saw https://github.com/michaelpq/pg_plugins/tree/master/decoder_raw which would be a perfect start to continueously index Postgresql changes into Elasticsearch.

**Comment by rmartignoni** [comment]
@jprante thanks for the promptly answer! 

I think that I was not able to clearly explain my scenario. I am trying to avoid syncing 5M data to update the accounts which come online/offline. Unfortunately I can't handle this on the application side since our users will be able to apply a filter on this column.

My first thought was to create a river to make a one time dump to ES (5M data), delete this river and created a new one to sync only the affected data which would be an average of **5k** data. I think river would easily handle this amount of data every minute.

My problem is that I didn't know how I would update the accounts which were not in the fresh batch to make them offline (the river would bring only the online ones). That's what my question is about. Is there a way to update documents before river send a new bulk?

#### Something like this 

```sql
-- before river
UPDATE accounts SET online = false;

UPDATE accounts SET online = true WHERE (accounts from river)
```

I am not sure if this would be either possible or performant.

**Comment by jprante** [comment]
You can set up a sequence of SQL statements, including updates.

I'm not sure how to get the where clause (accounts from river) though. This will need some experimenting.

**Comment by rmartignoni** [comment]
@jprante I was already using SQL statements to keep my ES data updated. I think I was not able to clearly explain my problem but we found a workaround to solve it. It may not be the optimal solution but it's the best we found to our application and river. We rely on triggers to determine the data which should be sent (updated) to ES.

Anyway, thanks for your promptly help!
