### ISSUE TITLE
QueryBuilders.matchPhrasePrefixQuery() for INTEGER Column is not working

### ISSUE THREAD

**Issue by snk28** [jprante/elasticsearch-river-jdbc#505]
I am unable to use QueryBuilders.matchPhrasePrefixQuery(fieldName, searchQuery) for INTEGER column. I am able to fetch the results if the fieldname is a VARCHAR column. If it is an INTEGER column, It is fetching the result which ever matches the exact value. 

For e.g) If there is a INTEGER column as CUSTOMER_NUMBER and have data like 12345684, 123477554, 1234, 12395645. and if i mention "1234" as search query in the above mentioned method... the results fetched is only "1234" and not "12345684, 123477554"
Please let me know which Java API should i use to fetch all those 3 values - "12345684, 123477554, 1234".

**Comment by jprante** [comment]
Use SQL-92 CAST function in SQL statement, e.g.

    select cast(customer_number as varchar(32)) as customer_string from ...

**Comment by snk28** [comment]
Thank you jprante... ;)
its working now using QueryBuilders.matchPhrasePrefixQuery() after casting as you mentioned... 
I thought of this idea earlier.. but didn't implement it.. instead was trying to find Java API method..
