### ISSUE TITLE
Older versions

### ISSUE THREAD

**Issue by bsimm** [jprante/elasticsearch-river-jdbc#507]
I had been using [this url](http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-river-jdbc/) to download some versions of this plugin that no longer seem to be there.  Are these older versions still hosted anywhere?

**Comment by jprante** [comment]
Sorry for the inconvenience. I have restored 1.0.3.4, 1.1.2.4, 1.2.4.5, 1.3.4.7

**Comment by bsimm** [comment]
Thanks!

**Comment by bsimm** [comment]
@jprante if you could put up an "elasticsearch-river-jdbc-1.4.4.0-plugin.zip" at that url I would really appreciate it.  consistency between links is key for me to support several versions of ES on live clusters.

**Comment by jprante** [comment]
Done.

I was told the assembly ID is not consistent with ES plugin zips but I can live with it either way.

**Comment by bsimm** [comment]
Thanks!
