### ISSUE TITLE
ES 1.5x and elasticsearch-river-jdbc 1.5 doesnt pull mysql data

### ISSUE THREAD

**Issue by aradhell** [jprante/elasticsearch-river-jdbc#509]
Hello

 I just installed ES 1.5 via RPM and installed elasticsearch-river-jdbc plugin and it doesnt work now, i also downloaded the com.mysql.jdbc_5.1.5.jar to plugins/jdbc/

 Two days ago i was using ES 1.4 and elasticsearch-river-jdbc it was working nicely..

PUT /_river/my_jdbc_river/_meta
{
"type" : "jdbc",
"jdbc" : {
"url" : "jdbc:mysql://xxxx:3306/xxx_db",
"user" : "xxx_db",
"password" : "pass",
"sql" : "select id,name FROM names",
"index" : "index",
"type" : "type"
}
}

 "plugins" : [ {
        "name" : "jdbc-1.5.0.0-197ef2e",
        "version" : "1.5.0.0",
        "description" : "JDBC plugin",
        "jvm" : true,
        "site" : false
      }]

**Comment by jprante** [comment]
Can you give some information about the error message?

**Comment by aradhell** [comment]
there isn't error msg on console or request response, river index seeing on shard. where can i find logs about plugin or what you want exactly?

**Comment by jprante** [comment]
There is the Elasticsearch log file.

**Comment by aradhell** [comment]
java.sql.SQLException: No suitable driver found for jdbc:mysql://

and

[2015-03-27 16:35:29,547][WARN ][river.jdbc.RiverThread   ] interrupted
[2015-03-27 16:35:29,548][ERROR][river.jdbc.RiverPipeline ] Future got interrupted
org.elasticsearch.ElasticsearchIllegalStateException: Future got interrupted


jdbc folder 
http://prntscr.com/6m4vp0

**Comment by jprante** [comment]
The JDBC driver is not recognized. Check file permissions on MySQL driver jar. Do not run Elasticsearch as root.

**Comment by aradhell** [comment]
http://prntscr.com/6m4z4z

jars are 777 and i m starting es by service elasticsearch start

**Comment by jprante** [comment]
You have two MySQL JDBC drivers in the folder, is that correct?

**Comment by aradhell** [comment]
http://prntscr.com/6m51ej

i have com.mysql.jdbc_5.1.5.jar
and mysql-connector-java-5.0.8-bin.jar

but i tried them one by one

**Comment by jprante** [comment]
The jars are both added to the classpath. Remove all but one MySQL driver.

**Comment by aradhell** [comment]
which driver shud i use ? installing plugin again

**Comment by aradhell** [comment]
i installed plugin again and added mysql-connector-java-5.1.33.jar to /jdbc and classpath it works now,
thank you
