### ISSUE TITLE
when-use-river-plugin-data-update-only-changes-or-all-index

### ISSUE THREAD

**Issue by astrung** [jprante/elasticsearch-river-jdbc#517]
Now i update mysql database,and elasticsearch data will be updated every 10 second. But i have a question for this action:When elasticsearch data be updated,it only change the change of mysql database,or delete and recreate index??If it recreate index,it takes long time when we work with bigdata??

**Comment by jprante** [comment]
What do you mean by delete/recreate index?

**Comment by astrung** [comment]
yes.i have a big table in MySql,and if we must delete/recreate this index for the table,we will wait in long time.

**Comment by astrung** [comment]
By this river, we can keep in sync between Elasticsearch and MySql with "autocommit","schedule" parameters right??But how to keep in sync???To keep in sync,when MySql databases change a record,we need change a document in index.When change this document,this river will only change a document or must recreate index and re-import all documents to change a record??

**Comment by jprante** [comment]
You have to set up an SQL statement to fetch rows from DB and index documents in Elasticsearch. You can also fetch rows by an SQL statement that can be used to delete documents in Elastisearch.

**Comment by astrung** [comment]
No.I meant:what did you do to keep in sync between Elasticsearch data and MySQL?How to keep in sync when we update MySQL data?I have done that by this river,but i want to know how to do that.It is neccessary to decide that i will use this river for my big table or not.

**Comment by jprante** [comment]
If you want to detect changes in MySQL, you would have to push the changes from MySQL to Elasticsearch. 

Such a push module must be implemented at DB side. It must use a custom data model and use an official ES client with custom logic.

This JDBC plugin for Elasticsearch is for pulling data out of a DB like MySQL in a generic way. Changes in the DB can not be detected from within Elasticsearch.

Note, Elasticsearch is not a database, there are no rows and columns to "sync". For "sync", you need both sides to agree upon entities which can be identified. In Elasticsearch, you have the ID of a document for identity. Rows in SQL do not have such an identity, there are primary keys, which are another concept, and only work on a table, not on table joins e.g.

**Comment by tiagoribeirof** [comment]
You can just map your id in your DB to be _id in your elasticSearch documents, this way the elastic will indentify when the document was changed or not.
