### ISSUE TITLE
mysql boolean field cannot be loaded to es right

### ISSUE THREAD

**Issue by jeffreyji666** [jprante/elasticsearch-river-jdbc#521]
As title, I have a boolean field in mysql table, I want it to be loaded to elasticsearch with mapping to boolean type, however It is integer type. 

I know this is because boolean in mysql is stored as tiny int 1 or 0, but Is there a way to map the boolean field mysql to elasticsearch boolean type?

**Comment by jprante** [comment]
Yes. Here is an example

https://gist.github.com/jprante/bac99931f8e419383bd8

	#!/bin/sh

	/usr/local/mysql/bin/mysql -u root test <<EOT
	drop table test;
	create table test (
		id integer,
		b boolean
	);
	insert into test values (1, FALSE);
	insert into test values (2, TRUE);
	EOT

	curl -XDELETE 'localhost:9200/_river/my_test_river/'

	curl -XDELETE 'localhost:9200/mytest'

	curl -XPOST 'localhost:9200/_river/my_test_river/_meta' -d '
	{
		"type" : "jdbc",
		"jdbc" : {
			"url" : "jdbc:mysql://localhost:3306/test",
			"user" : "",
			"password" : "",
			"sql" : "select id as _id, IF(b,'"'"'true'"'"','"'"'false'"'"') as b from test",
			"index" : "mytest",
			"type" : "mydocs",
			"index_settings" : { },
			"type_mapping" : {
				  "mydocs" : {
					  "properties" : {
						   "b" : { 
								"type" : "boolean"
						   }
					  }
				  }
			}
		}
	}
	'

	echo "sleeping while river should run..."

	sleep 5

	curl -XGET 'localhost:9200/mytest/_mapping?pretty'

	curl -XPOST 'localhost:9200/mytest/_search?pretty' -d '
	{
	  "query" : {
		"filtered" : {
		   "query": {
			  "match_all": {
			   }           
		   },
		   "filter" : {
			  "term" : {
				  "b" : true
			  }
		   }
		}
	  }
	}'

	curl -XDELETE 'localhost:9200/_river/my_test_river/'
